[package]
name = "bioscape-server"
version = "0.1.0"
edition = "2018"

[dependencies]
bioscape-common = { path = "../common" }
bincode = "1.3"
crossbeam-channel = "0.5"
hecs = "0.6"
lazy_static = "1.4"

# Logging
log = "0.4"
env_logger = "0.9"
dotenv = "0.15"
