[package]
name = "bioscape-server"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = { version = "1.9", features = ["attributes"]}
futures = "0.3"
bincode = "1.3"
crossbeam-channel = "0.5"
lazy_static = "1.4"
bioscape-common = { path = "../common" }
hecs = "0.5"

# Logging
log = "0.4"
env_logger = "0.8"
dotenv = "0.15"
